import Head from "next/head";
import { NextPage } from "next";
import { ThemeProvider } from "styled-components";
import Navbar from "../components/main_modules/navbar";
import { GlobalStyle } from "../styles/globalStyles";
import Banner from "../components/main_modules/Banner";
import Services from "../components/main_modules/services";
import Project from "../components/main_modules/project";

export type theme = {
  backgroundColors: {
    primary: string;
  };

  body: string;
  textColors: {
    primary: string;
    secondary:string
  };

  buttonColors: {
    bg_primary: string;
    tex_primary: string;
    tex_secondary?:string
  };
  serviceBodyColor:{
    primary:string
  }
};

const darkTheme: theme = {
  backgroundColors: {
    primary: "#fff",
  },
  body: "rgb(31, 38, 49)",
  textColors: {
    primary: "#d9dadb",
    secondary:"#73797c"
  },
  buttonColors: {
    bg_primary: "#fefefe",
    tex_primary: "#d9dadb",
    tex_secondary:"#212b36"
  },
  serviceBodyColor:{
    primary:"#161c24"
  }
};

const lightTheme: theme = {
  backgroundColors: {
    primary: "#fff",
  },
  body: "rgb(31, 38, 49)",
  textColors: {
    primary: "#000",
    secondary:"#73797c"
  },
  buttonColors: {
    bg_primary: "#fefefe",
    tex_primary: "#d9dadb",
  },
  serviceBodyColor:{
    primary:"#161c24"
  }
};

const Home: NextPage = () => {
  return (
    <>
      <ThemeProvider theme={darkTheme}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <GlobalStyle />
          <Navbar />
          <Banner />
          <Services />
          <Project />
        </main>
      </ThemeProvider>
    </>
  );
};

export default Home;
